service: auction-service

frameworkVersion: ^3.12.0

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-cloudside-plugin
  - serverless-offline

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.auctions-table.name}
    MAIL_QUEUE_URL: ${self:custom.mail-queue.url}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - ${self:custom.auctions-table.arn}
        - !Join ["/", ["${self:custom.auctions-table.arn}", "index", "*"]]
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: ${self:custom.mail-queue.arn}
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - arn:aws:ses:*

resources:
  Resources:
    # ref: https://serverless-stack.com/chapters/configure-cognito-user-pool-in-serverless.html
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:provider.stage}-user-pool
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false

    MailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.mail-queue.name}

    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  # Print out the Id of the User Pool that is created
  Outputs:
    # Cognito
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient

    # MailQueue
    MailQueueArn:
      Value: ${self:custom.mail-queue.arn}
      Export:
        Name: ${self:custom.mail-queue.name}-Arn
    MailQueueUrl:
      Value: ${self:custom.mail-queue.url}
      Export:
        Name: ${self:custom.mail-queue.name}-Url

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  getAuction:
    handler: src/handlers/getAuctionById.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}/bid
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mail-queue.arn}
          batchSize: 1

custom:
  user-pool:
    arn: !GetAtt CognitoUserPool.Arn
  auctions-table:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
    printOutput: true
  mail-queue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
